### ISSUE TITLE
Where are the vendor sources?

### ISSUE THREAD

**Issue by willem640** [OpenKirin/android_vendor_honor_berlin#1]
I have seen multiple ROMs with a a separate vendor.img, but where are the sources?

**Comment by willem640** [comment]
By the way those roms were openkirin

**Comment by XePeleato** [comment]
Hi, there's no source for the vendor partition because the binaries contained there are precompiled by Huawei, so we don't have access to the source.

Please let me know if I have answered to your question so that I can close the issue.

**Comment by willem640** [comment]
Okay, I see. 
But why do we have to flash a vendor.img for custom ROMs like LineageOS and ResurrectionRemix?
And not for AOSPA (Paranoid android)

**Comment by willem640** [comment]
Closing the issue because it is not relevant or necessary anymore, but please answer my previous question

**Comment by XePeleato** [comment]
You actually flash it as well while installing AOSPA, but it's integrated into the zip package so it's automatic.

**Comment by willem640** [comment]
okay, didn't know that
