### ISSUE TITLE
why do we have to flash a custom vendor.img?

### ISSUE THREAD

**Issue by willem640** [OpenKirin/android_vendor_honor_berlin#2]
why do we have to flash a custom vendor.img when installing openkirin ROMs when these are provided by huawei. where did you get the vendor.img from? and why is this proprietary for openkirin based stuff

**Comment by XePeleato** [comment]
Simple, we got it from Huawei like everyone else, and removed the binaries that were not necessary.
It's proprietary because we don't have the source, there's no way around that.

**Comment by willem640** [comment]
okay, thanks!
