### ISSUE TITLE
Can not compile AospExtended

### ISSUE THREAD

**Issue by pomelohan** [OpenKirin/android_vendor_honor_berlin#3]
I am from China, so I used Google Translate.
I have completed the source code synchronization, but the implementation of the preparation of the environment when the order suggested that the following: root @ ubuntu: / media / psf / Android #. Build / envsetup.sh
including device / honor / berlin / vendorsetup.sh
including vendor / aosp / vendorsetup.sh
including sdk / bash_completion / adb.bash
root @ ubuntu: / media / psf / Android # lunch lineage_berlin-userdebug
build / core / product_config.mk: 234: *** Can not locate config makefile for product "lineage_berlin".
Device berlin not found. Attempting to retrieve device repository from AospExtended-Devices Github (http://github.com/AospExtended-Devices).
Repository for berlin not found in the AospExtended-Devices Github repository list.
If this is in error, you may need to manually add it to your .repo / local_manifests / aex_manifest.xml
build / core / product_config.mk: 234: *** Can not locate config makefile for product "lineage_berlin".

** Do not have a product spec for: 'lineage_berlin'
** Do you have the right repo manifest?
build / core / product_config.mk: 234: *** Can not locate config makefile for product "lineage_berlin".
build / core / product_config.mk: 234: *** Can not locate config makefile for product "lineage_berlin".

** Do not have a product spec for: 'lineage_berlin'
** Do you have the right repo manifest?

Hope to answer my issues!
Thank you very much!
Hava a good day!

**Comment by XePeleato** [comment]
It isn't a problem from our tree, so technically, this isn't an issue in our end, but yours, since you haven't synced the sources correctly, I recommend you to try again, this process is highly documented and there are tons of examples online.

Since there's nothing to fix, I'll close the issue.

**Comment by pomelohan** [comment]
Ok,Thank you very much . But I tried it at least three times. Can you help me to build it ?
Hava a good day!

**Comment by Huawei-Dev** [comment]
If you need some help, I can help you  ...
Just download from our OpenKirin github device tree "android_device_honor_berlin" and put this on your source code of AOSPExt into device/honor/berlin ... do the same for vendor & kernel ... right now you are good to build without issues !
